// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpOkDFrKXrxXo2qZVyCJ3kpyhZXLgN9I8',
    appId: '1:338315767506:web:8c13d96329c3de970f870b',
    messagingSenderId: '338315767506',
    projectId: 'wafrhaa',
    authDomain: 'wafrhaa.firebaseapp.com',
    storageBucket: 'wafrhaa.firebasestorage.app',
    measurementId: 'G-RK7EHNC082',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_E4iRDPonRPJsz07dTdBq2GLTQYOG0eo',
    appId: '1:338315767506:android:4098ecea4e90a21d0f870b',
    messagingSenderId: '338315767506',
    projectId: 'wafrhaa',
    storageBucket: 'wafrhaa.firebasestorage.app',
  );

}